package constants

var DEFAULT_KEY_USAGE = "ENCRYPT_DECRYPT"

var SYMMETRIC_ENCRYPTION_KEY_USAGES []string = []string{"ENCRYPT_DECRYPT"}

var ASYMMETRIC_ENCRYPTION_KEY_USAGES []string = []string{"ENCRYPT_DECRYPT ", "SIGN_VERIFY"}
