package constants

var (
	ENCRYPT_DECRYPT = "ENCRYPT_DECRYPT"
	SIGN_VERIFY     = "SIGN_VERIFY"
)

var DEFAULT_KEY_USAGE = ENCRYPT_DECRYPT

var SYMMETRIC_ENCRYPTION_KEY_USAGES []string = []string{ENCRYPT_DECRYPT}

var ASYMMETRIC_ENCRYPTION_KEY_USAGES []string = []string{ENCRYPT_DECRYPT, SIGN_VERIFY}

var KEY_USAGES []string = append(SYMMETRIC_ENCRYPTION_KEY_USAGES, ASYMMETRIC_ENCRYPTION_KEY_USAGES...)
