package constants

var DEFAULT_KEY_SPEC = "SYMMETRIC_DEFAULT"

var SYMMETRIC_KEY_SPECS []string = []string{"SYMMETRIC_DEFAULT"}

var ASYMMETRIC_KEY_SPECS []string = []string{RSA_2048, RSA_3072, RSA_4096}

var KEY_SPECS []string = append(SYMMETRIC_KEY_SPECS, ASYMMETRIC_KEY_SPECS...)

var (
	RSA_2048 = "RSA_2048"
	RSA_3072 = "RSA_3072"
	RSA_4096 = "RSA_4096"
)
